# Generated by Django 4.0.6 on 2022-07-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
    ]
