# Generated by Django 4.0.6 on 2022-07-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_alter_movie_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='test_field',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
