# Generated by Django 4.0.6 on 2022-07-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_alter_movie_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='test_field',
        ),
    ]
