# Generated by Django 4.0.6 on 2022-07-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_genre_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
