# Generated by Django 4.0.6 on 2022-07-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_movie_country_of_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country_of_origin',
            field=models.CharField(blank=True, choices=[('UNITED STATES', 'UNITED STATES'), ('ESTONIA', 'ESTONIA')], max_length=30, null=True),
        ),
    ]
