# Generated by Django 4.0.6 on 2022-07-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0020_actor_director_country_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='viewer.actor'),
        ),
    ]
